name: Install

on: [push]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Build and install library
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        sudo cmake --build build --target install
        rm -rf build

    - name: Configure
      run: cmake -S periodic_function/tests -B build -DTEST_INSTALLED_VERSION=1

    - name: Build
      run: cmake --build build --config Debug -j4

    - name: Run tests
      run: |
        cd build
        ctest --build-config Debug
