name: Ubuntu

on: [push]

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: configure
      run: cmake -S . -B build -DENABLE_TEST_COVERAGE=1

    - name: build
      run: cmake --build build --config Debug -j4

    - name: test
      run: |
        cd build
        ctest --build-config Debug

    - name: Collect code coverage
      run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
